### PR TITLE
Added align* methods

### PR DESCRIPTION
**Pull request by YuriGor**
Just added 4 simple methods: alignTop, alignBottom, alignLeft and alignRight.
Methods made on top  of "center" method, just another offsets used.

Purpose of this methods - to be able to set additional initial image positions after calling "fit" method.

### CODE REVIEW

**Comment by matiasgagliano** [comment]
Hi @YuriGor, the effort is appreciated but the pull request can't be accepted.

First of all changes should be applied to source files (in CoffeeScript). When work is done they should  be compiled and minified commiting both the source and the js files.

And second, as stated [here](//github.com/matiasgagliano/guillotine#more-features), the aim of the plugin is to be as simple as posible and to provide a general API, specific features are left for users to implement. So, I'd be better to implement a single general method like the *setData* example in #6.

**Comment by YuriGor** [comment]
Ok, I'll learn a coffescript a bit(it looks useful) and will do a next try,
but please, define your "simple as possible".

Does adding some simple methods break your philosophy of simplicity?
I thought this 'align*' methods are at the same level of the simplicity, as 'center' method actually is.

Should I add one method 'align' instead? 
It will take string argument: 'center', 'left', 'top', 'right' or 'bottom',
and 'center' method will become just shorthand for align('center')? (we should keep 'center' method for BC)

But as i see, your plugin is not ready to have methods with arguments now, so i should rewrite '# Plugin's API' block of code, should I?

And which minifier should i use? uglifyJS? UglifyJS2? With default parameters?

I hope my activity is not very annoying: as you can see, i have no experience with opensource development yet.

**Comment by matiasgagliano** [comment]
With *as simple as possible* I mean an API as *small*, *flexible* and *general* as possible. This allows the plugin to be really *lightweight* and *easy* to use but also flexible enough to allow implementing complex features in more specific use cases like yours.

Only one *align* method is step forward, and it wouldn't be a problem to break the API if moved to the next major version ([semantic versioning](//semver.org)). But still *align* would be a particular case of what you can do with *setData* that provides much more possibilities.

```javascript
var alignLeft = function (pic) {
  pic.guillotine('setData', { x: 0 }) 
}

var alignRight = function (pic) {
  // This may be improved by providing the image dimentions.
  var win = pic.parents('.guillotine-window').first(),
      x = ( pic.width() / win.width() ) * pic.guillotine('getData')['w']
  pic.guillotine('setData', { x: x })
}

// ...
```

The *setData* method is already developed and it's fairly easy to implement getting the plugin's instance as done [here](//github.com/matiasgagliano/guillotine/issues/6#issuecomment-53178560), so for now I'm going to focus on some inner redesigns that arose from the work done on version 1.3.0.

The plugin's use scope has grown far beyond its initial purpose of just allowing *users* to choose an area to crop, which didn't require to programmatically transform or move the image. I intend to extend the plugin to meet the needs of the community but as long as its simplicity isn't compromised. It should [do one thing and do it well](//en.wikipedia.org/wiki/Unix_philosophy).

Regarding the minifier, what matters is to get the smallest size possible. I use UglifyJS2 with mangling and compression but anything else may be used as long as it works and the size is smaller.

As a last though, in my experience developing open source has been an very fulfilling experience but don't rush at it. Get to know really well the existing code and the practices used, take time to think things through and keep in mind that other people will enjoy or have to bear with your code.

**Comment by YuriGor** [comment]
Thank you for your patience.

So, for now, to achieve my goal it's better to use implementation of [setData method] (https://github.com/matiasgagliano/guillotine/issues/6#issuecomment-53178560)
But i missed the point, will this method be the part of API in next versions of plugin or not?

**Comment by matiasgagliano** [comment]
Yes, many have asked for ways to set one or another peace of data so by adding *setData* I'll address most of these concerns. Maybe it doesn't end up exactly as in the example but it will be very close.

**Pull request closed without merging**
