### PR TITLE
publish to npm

### PR DESCRIPTION
**Pull request by leider**
If you don't want to set up an account there, I could do that for you.

### CODE REVIEW

**Comment by matiasgagliano** [comment]
It's not published because when I started with it there wasn't a clear or at least standard way to require front-end scrips and their assets (CSS, images, etc.) from npm modules.

Now with the advent of bundlers and [plugins.jquery.com](plugins.jquery.com) being inactive it might be time to publish it. Give me some time to look into it and I'll publish it.

**Comment by leider** [comment]
Thanks

**Comment by matiasgagliano** [comment]
[Guillotine](https://www.npmjs.com/package/guillotine) is on npm now.

I guess you were really [eager](https://www.npmjs.com/package/jquery-guillotine-leider) to have it published but now that there's an official release it'd be nice if you could take the mirror down to avoid confusion.

Thanks for supporting Guillotine!

**Comment by leider** [comment]
\o/. Will do. 

Thanks a lot!!!!

**Comment by leider** [comment]
DONE. The webpage in npm is still there. I don't have a clue about how to remove it. The modules are gone.

**Comment by matiasgagliano** [comment]
It's all gone now, thanks!

**Pull request closed without merging**
